// <auto-generated />
using System;
using CoronaApp.Dal;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CoronaApp.Dal.Migrations;

[DbContext(typeof(CoronaDbContext))]
partial class CoronaDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("Relational:MaxIdentifierLength", 128)
            .HasAnnotation("ProductVersion", "5.0.12")
            .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

        modelBuilder.Entity("CoronaApp.Api.Logging.LoggingMessege", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Level")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("LogEvent")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Message")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Properties")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ThreadId")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTimeOffset>("Timestamp")
                    .HasColumnType("datetimeoffset");

                b.HasKey("Id");

                b.ToTable("Messeges");
            });

        modelBuilder.Entity("CoronaApp.Services.Models.Location", b =>
            {
                b.Property<int>("LocaionId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                b.Property<string>("Address")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("City")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("EndDate")
                    .HasColumnType("datetime2");

                b.Property<string>("PatientId")
                    .HasColumnType("nvarchar(9)");

                b.Property<DateTime>("StartDate")
                    .HasColumnType("datetime2");

                b.HasKey("LocaionId");

                b.HasIndex("PatientId");

                b.ToTable("Locations");
            });

        modelBuilder.Entity("CoronaApp.Services.Models.Patient", b =>
            {
                b.Property<string>("Id")
                    .HasMaxLength(9)
                    .HasColumnType("nvarchar(9)");

                b.Property<int>("age")
                    .HasColumnType("int");

                b.Property<string>("name")
                    .HasColumnType("nvarchar(max)");

                b.HasKey("Id");

                b.ToTable("Patients");
            });

        modelBuilder.Entity("CoronaApp.Services.Models.Location", b =>
            {
                b.HasOne("CoronaApp.Services.Models.Patient", "Patient")
                    .WithMany()
                    .HasForeignKey("PatientId");

                b.Navigation("Patient");
            });
#pragma warning restore 612, 618
    }
}
